/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    users: User;
    media: Media;
    'university-media': UniversityMedia;
    tryouts: Tryout;
    questions: Question;
    'tryout-attempts': TryoutAttempt;
    'tryout-payments': TryoutPayment;
    'tryout-scores': TryoutScore;
    'tryout-explanations': TryoutExplanation;
    universities: University;
    'university-programs': UniversityProgram;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    universities: {
      programList: 'university-programs';
    };
  };
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'university-media': UniversityMediaSelect<false> | UniversityMediaSelect<true>;
    tryouts: TryoutsSelect<false> | TryoutsSelect<true>;
    questions: QuestionsSelect<false> | QuestionsSelect<true>;
    'tryout-attempts': TryoutAttemptsSelect<false> | TryoutAttemptsSelect<true>;
    'tryout-payments': TryoutPaymentsSelect<false> | TryoutPaymentsSelect<true>;
    'tryout-scores': TryoutScoresSelect<false> | TryoutScoresSelect<true>;
    'tryout-explanations': TryoutExplanationsSelect<false> | TryoutExplanationsSelect<true>;
    universities: UniversitiesSelect<false> | UniversitiesSelect<true>;
    'university-programs': UniversityProgramsSelect<false> | UniversityProgramsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: string;
  role: 'super-admin' | 'admin' | 'volunteer';
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  email: string;
  clerkUserId?: string | null;
  profileCompleted?: boolean | null;
  username?: string | null;
  fullName?: string | null;
  whatsapp?: string | null;
  schoolOrigin?: string | null;
  grade?: ('10' | '11' | '12' | 'gap_year') | null;
  targetPTN?: string | null;
  targetMajor?: string | null;
  targetPTN2?: string | null;
  targetMajor2?: string | null;
  targetPTN3?: string | null;
  targetMajor3?: string | null;
  paid?: boolean | null;
  payment?: (string | null) | Media;
  roles?: ('super-admin' | 'admin' | 'user')[] | null;
  dateOfBirth?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  /**
   * Terkait dengan Batch Tryout (Opsional)
   */
  relatedTryout?: (string | null) | Tryout;
  /**
   * ID atau Nama Subtest Terkait (Opsional)
   */
  relatedSubtest?: string | null;
  /**
   * Nomor Soal Terkait (Opsional)
   */
  relatedQuestionNumber?: number | null;
  _key?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tryouts".
 */
export interface Tryout {
  id: string;
  title: string;
  /**
   * Auto-generated from title if empty
   */
  slugField?: string | null;
  /**
   * WIB (GMT+7)
   */
  dateOpen: string;
  /**
   * WIB (GMT+7)
   */
  dateClose: string;
  /**
   * When scores become visible to students. WIB (GMT+7)
   */
  scoreReleaseDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "university-media".
 */
export interface UniversityMedia {
  id: string;
  /**
   * Teks alternatif untuk aksesibilitas dan SEO.
   */
  alt: string;
  _key?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions".
 */
export interface Question {
  id: string;
  duration: number;
  subtest?: ('PU' | 'PK' | 'PM' | 'LBE' | 'LBI' | 'PPU' | 'KMBM') | null;
  tryout: string | Tryout;
  title: string;
  tryoutQuestions?:
    | {
        question: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        tryoutAnswers: {
          answer: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          isCorrect: boolean;
          id?: string | null;
          blockName?: string | null;
          blockType: 'tryoutAnswer';
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'tryoutQuestion';
      }[]
    | null;
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tryout-attempts".
 */
export interface TryoutAttempt {
  id: string;
  user: string | User;
  tryout: string | Tryout;
  answers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  flags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  questionResults?:
    | {
        subtestId: string;
        questionId: string;
        questionNumber: number;
        selectedLetter?: string | null;
        correctLetter?: string | null;
        isCorrect?: boolean | null;
        id?: string | null;
      }[]
    | null;
  status: 'started' | 'completed';
  startedAt?: string | null;
  /**
   * Authoritative server timestamp when the active subtest started.
   */
  subtestStartedAt?: string | null;
  /**
   * Authoritative server deadline for the current active subtest.
   */
  subtestDeadlineAt?: string | null;
  completedAt?: string | null;
  /**
   * Index of the currently active subtest (0-based).
   */
  currentSubtest?: number | null;
  /**
   * Internal exam state (running vs bridging).
   */
  examState?: ('running' | 'bridging') | null;
  /**
   * Bridging expiry time (if currently bridging).
   */
  bridgingExpiry?: string | null;
  /**
   * Remaining seconds at last backup.
   */
  secondsRemaining?: number | null;
  /**
   * Percentage of correct answers.
   */
  score?: number | null;
  correctAnswersCount?: number | null;
  totalQuestionsCount?: number | null;
  /**
   * Index of the current question in the active subtest (0-based).
   */
  currentQuestionIndex?: number | null;
  processedBatchIds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Selected tryout result plan.
   */
  resultPlan?: ('none' | 'free' | 'paid') | null;
  /**
   * Elapsed time (seconds) per subtest, mapped by subtestId.
   */
  subtestDurations?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * List user yang sudah melakukan pembayaran manual (untuk verifikasi).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tryout-payments".
 */
export interface TryoutPayment {
  id: string;
  /**
   * User yang melakukan pembayaran
   */
  user: string | User;
  tryout: string | Tryout;
  attempt: string | TryoutAttempt;
  status: 'pending' | 'verified' | 'rejected';
  program?: string | null;
  /**
   * Nominal pembayaran
   */
  amount?: number | null;
  paymentDate?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tryout-scores".
 */
export interface TryoutScore {
  id: string;
  user: string | User;
  tryout: string | Tryout;
  /**
   * PU
   */
  score_PU?: number | null;
  /**
   * PK
   */
  score_PK?: number | null;
  /**
   * PM
   */
  score_PM?: number | null;
  /**
   * LBE
   */
  score_LBE?: number | null;
  /**
   * LBI
   */
  score_LBI?: number | null;
  /**
   * PPU
   */
  score_PPU?: number | null;
  /**
   * KMBM
   */
  score_KMBM?: number | null;
  finalScore: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pembahasan Tryout dalam bentuk file PDF.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tryout-explanations".
 */
export interface TryoutExplanation {
  id: string;
  /**
   * Name of the explanation document.
   */
  title: string;
  /**
   * Select the Tryout batch this explanation belongs to.
   */
  tryout: string | Tryout;
  /**
   * Upload the PDF file containing the explanations.
   */
  pdf: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "universities".
 */
export interface University {
  id: string;
  name: string;
  /**
   * Otomatis di-generate dari nama. Bisa diedit manual.
   */
  slugField?: string | null;
  abbreviation?: string | null;
  npsn?: string | null;
  status?: ('negeri' | 'swasta' | 'ptk') | null;
  accreditation?: string | null;
  address?: string | null;
  district?: string | null;
  city?: string | null;
  province?: string | null;
  website?: string | null;
  pddiktiId?: string | null;
  image?: (string | null) | UniversityMedia;
  coverImage?: (string | null) | UniversityMedia;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  visionMission?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  programCount?: number | null;
  programsWithMetricsCount?: number | null;
  completenessScore?: number | null;
  /**
   * Program studi yang terhubung dengan universitas ini (dari koleksi University Programs).
   */
  programList?: {
    docs?: (string | UniversityProgram)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Program studi per-universitas. Data ini di-generate dari field `programs` lama untuk meringankan dokumen universitas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "university-programs".
 */
export interface UniversityProgram {
  id: string;
  university: string | University;
  universityName?: string | null;
  abbreviation?: string | null;
  status?: string | null;
  universityAccreditation?: string | null;
  name: string;
  faculty?: string | null;
  level?: string | null;
  category?: ('snbt' | 'snbp' | 'mandiri') | null;
  accreditation?: string | null;
  /**
   * Diisi otomatis dari data scraping. Boleh dikosongkan untuk input manual.
   */
  metrics?:
    | {
        year?: string | null;
        capacity?: number | null;
        applicants?: number | null;
        passingPercentage?: string | null;
        predictedApplicants?: number | null;
        admissionMetric?: string | null;
        avgUkt?: string | null;
        maxUkt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Dipakai untuk migrasi dan menjaga referensi dari data lama.
   */
  legacyProgramId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'admins';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'university-media';
        value: string | UniversityMedia;
      } | null)
    | ({
        relationTo: 'tryouts';
        value: string | Tryout;
      } | null)
    | ({
        relationTo: 'questions';
        value: string | Question;
      } | null)
    | ({
        relationTo: 'tryout-attempts';
        value: string | TryoutAttempt;
      } | null)
    | ({
        relationTo: 'tryout-payments';
        value: string | TryoutPayment;
      } | null)
    | ({
        relationTo: 'tryout-scores';
        value: string | TryoutScore;
      } | null)
    | ({
        relationTo: 'tryout-explanations';
        value: string | TryoutExplanation;
      } | null)
    | ({
        relationTo: 'universities';
        value: string | University;
      } | null)
    | ({
        relationTo: 'university-programs';
        value: string | UniversityProgram;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: string | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'admins';
    value: string | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  email?: T;
  clerkUserId?: T;
  profileCompleted?: T;
  username?: T;
  fullName?: T;
  whatsapp?: T;
  schoolOrigin?: T;
  grade?: T;
  targetPTN?: T;
  targetMajor?: T;
  targetPTN2?: T;
  targetMajor2?: T;
  targetPTN3?: T;
  targetMajor3?: T;
  paid?: T;
  payment?: T;
  roles?: T;
  dateOfBirth?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  relatedTryout?: T;
  relatedSubtest?: T;
  relatedQuestionNumber?: T;
  _key?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "university-media_select".
 */
export interface UniversityMediaSelect<T extends boolean = true> {
  alt?: T;
  _key?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tryouts_select".
 */
export interface TryoutsSelect<T extends boolean = true> {
  title?: T;
  slugField?: T;
  dateOpen?: T;
  dateClose?: T;
  scoreReleaseDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions_select".
 */
export interface QuestionsSelect<T extends boolean = true> {
  duration?: T;
  subtest?: T;
  tryout?: T;
  title?: T;
  tryoutQuestions?:
    | T
    | {
        tryoutQuestion?:
          | T
          | {
              question?: T;
              tryoutAnswers?:
                | T
                | {
                    tryoutAnswer?:
                      | T
                      | {
                          answer?: T;
                          isCorrect?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tryout-attempts_select".
 */
export interface TryoutAttemptsSelect<T extends boolean = true> {
  user?: T;
  tryout?: T;
  answers?: T;
  flags?: T;
  questionResults?:
    | T
    | {
        subtestId?: T;
        questionId?: T;
        questionNumber?: T;
        selectedLetter?: T;
        correctLetter?: T;
        isCorrect?: T;
        id?: T;
      };
  status?: T;
  startedAt?: T;
  subtestStartedAt?: T;
  subtestDeadlineAt?: T;
  completedAt?: T;
  currentSubtest?: T;
  examState?: T;
  bridgingExpiry?: T;
  secondsRemaining?: T;
  score?: T;
  correctAnswersCount?: T;
  totalQuestionsCount?: T;
  currentQuestionIndex?: T;
  processedBatchIds?: T;
  resultPlan?: T;
  subtestDurations?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tryout-payments_select".
 */
export interface TryoutPaymentsSelect<T extends boolean = true> {
  user?: T;
  tryout?: T;
  attempt?: T;
  status?: T;
  program?: T;
  amount?: T;
  paymentDate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tryout-scores_select".
 */
export interface TryoutScoresSelect<T extends boolean = true> {
  user?: T;
  tryout?: T;
  score_PU?: T;
  score_PK?: T;
  score_PM?: T;
  score_LBE?: T;
  score_LBI?: T;
  score_PPU?: T;
  score_KMBM?: T;
  finalScore?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tryout-explanations_select".
 */
export interface TryoutExplanationsSelect<T extends boolean = true> {
  title?: T;
  tryout?: T;
  pdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "universities_select".
 */
export interface UniversitiesSelect<T extends boolean = true> {
  name?: T;
  slugField?: T;
  abbreviation?: T;
  npsn?: T;
  status?: T;
  accreditation?: T;
  address?: T;
  district?: T;
  city?: T;
  province?: T;
  website?: T;
  pddiktiId?: T;
  image?: T;
  coverImage?: T;
  description?: T;
  visionMission?: T;
  programCount?: T;
  programsWithMetricsCount?: T;
  completenessScore?: T;
  programList?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "university-programs_select".
 */
export interface UniversityProgramsSelect<T extends boolean = true> {
  university?: T;
  universityName?: T;
  abbreviation?: T;
  status?: T;
  universityAccreditation?: T;
  name?: T;
  faculty?: T;
  level?: T;
  category?: T;
  accreditation?: T;
  metrics?:
    | T
    | {
        year?: T;
        capacity?: T;
        applicants?: T;
        passingPercentage?: T;
        predictedApplicants?: T;
        admissionMetric?: T;
        avgUkt?: T;
        maxUkt?: T;
        id?: T;
      };
  legacyProgramId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}