/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tryouts: Tryout;
    questions: Question;
    'tryout-attempts': TryoutAttempt;
    'tryout-payments': TryoutPayment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tryouts: TryoutsSelect<false> | TryoutsSelect<true>;
    questions: QuestionsSelect<false> | QuestionsSelect<true>;
    'tryout-attempts': TryoutAttemptsSelect<false> | TryoutAttemptsSelect<true>;
    'tryout-payments': TryoutPaymentsSelect<false> | TryoutPaymentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  username: string;
  fullName?: string | null;
  whatsapp?: string | null;
  schoolOrigin?: string | null;
  grade?: ('10' | '11' | '12' | 'gap_year') | null;
  targetPTN?: string | null;
  targetMajor?: string | null;
  targetPTN2?: string | null;
  targetMajor2?: string | null;
  paid?: boolean | null;
  payment?: (string | null) | Media;
  roles?: ('super-admin' | 'admin' | 'user')[] | null;
  dateOfBirth?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  _key?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tryouts".
 */
export interface Tryout {
  id: string;
  title: string;
  'Date Open': string;
  'Date Open_tz': SupportedTimezones;
  'Date Close': string;
  'Date Close_tz': SupportedTimezones;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions".
 */
export interface Question {
  id: string;
  /**
   * Waktu pengerjaan untuk subtes ini dalam menit.
   */
  duration: number;
  subtest?: ('PU' | 'PK' | 'PM' | 'LBE' | 'LBI' | 'PPU' | 'KMBM') | null;
  tryout: string | Tryout;
  title: string;
  tryoutQuestions?:
    | {
        question: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        tryoutAnswers: {
          answer: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          isCorrect: boolean;
          id?: string | null;
          blockName?: string | null;
          blockType: 'tryoutAnswer';
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'tryoutQuestion';
      }[]
    | null;
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tryout-attempts".
 */
export interface TryoutAttempt {
  id: string;
  user: string | User;
  tryout: string | Tryout;
  answers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  flags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  questionResults?:
    | {
        subtestId: string;
        questionId: string;
        questionNumber: number;
        selectedLetter?: string | null;
        correctLetter?: string | null;
        isCorrect?: boolean | null;
        id?: string | null;
      }[]
    | null;
  status: 'started' | 'completed';
  startedAt?: string | null;
  completedAt?: string | null;
  /**
   * Index subtes yang sedang dikerjakan (0-based).
   */
  currentSubtest?: number | null;
  /**
   * State internal ujian (pengerjaan vs istirahat antar subtes).
   */
  examState?: ('running' | 'bridging') | null;
  /**
   * Waktu berakhirnya bridging (jika sedang bridging).
   */
  bridgingExpiry?: string | null;
  /**
   * Sisa waktu (detik) saat penyimpanan terakhir.
   */
  secondsRemaining?: number | null;
  /**
   * Persentase jawaban benar.
   */
  score?: number | null;
  correctAnswersCount?: number | null;
  totalQuestionsCount?: number | null;
  /**
   * Index soal yang sedang dikerjakan di subtes saat ini (0-based).
   */
  currentQuestionIndex?: number | null;
  processedBatchIds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Paket hasil tryout yang dipilih peserta.
   */
  resultPlan?: ('none' | 'free' | 'paid') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * List user yang sudah melakukan pembayaran manual (untuk verifikasi).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tryout-payments".
 */
export interface TryoutPayment {
  id: string;
  /**
   * User yang melakukan pembayaran
   */
  user: string | User;
  tryout: string | Tryout;
  attempt: string | TryoutAttempt;
  status: 'pending' | 'verified' | 'rejected';
  program?: string | null;
  /**
   * Nominal pembayaran
   */
  amount?: number | null;
  paymentDate?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'tryouts';
        value: string | Tryout;
      } | null)
    | ({
        relationTo: 'questions';
        value: string | Question;
      } | null)
    | ({
        relationTo: 'tryout-attempts';
        value: string | TryoutAttempt;
      } | null)
    | ({
        relationTo: 'tryout-payments';
        value: string | TryoutPayment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  fullName?: T;
  whatsapp?: T;
  schoolOrigin?: T;
  grade?: T;
  targetPTN?: T;
  targetMajor?: T;
  targetPTN2?: T;
  targetMajor2?: T;
  paid?: T;
  payment?: T;
  roles?: T;
  dateOfBirth?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _key?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tryouts_select".
 */
export interface TryoutsSelect<T extends boolean = true> {
  title?: T;
  'Date Open'?: T;
  'Date Open_tz'?: T;
  'Date Close'?: T;
  'Date Close_tz'?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions_select".
 */
export interface QuestionsSelect<T extends boolean = true> {
  duration?: T;
  subtest?: T;
  tryout?: T;
  title?: T;
  tryoutQuestions?:
    | T
    | {
        tryoutQuestion?:
          | T
          | {
              question?: T;
              tryoutAnswers?:
                | T
                | {
                    tryoutAnswer?:
                      | T
                      | {
                          answer?: T;
                          isCorrect?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tryout-attempts_select".
 */
export interface TryoutAttemptsSelect<T extends boolean = true> {
  user?: T;
  tryout?: T;
  answers?: T;
  flags?: T;
  questionResults?:
    | T
    | {
        subtestId?: T;
        questionId?: T;
        questionNumber?: T;
        selectedLetter?: T;
        correctLetter?: T;
        isCorrect?: T;
        id?: T;
      };
  status?: T;
  startedAt?: T;
  completedAt?: T;
  currentSubtest?: T;
  examState?: T;
  bridgingExpiry?: T;
  secondsRemaining?: T;
  score?: T;
  correctAnswersCount?: T;
  totalQuestionsCount?: T;
  currentQuestionIndex?: T;
  processedBatchIds?: T;
  resultPlan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tryout-payments_select".
 */
export interface TryoutPaymentsSelect<T extends boolean = true> {
  user?: T;
  tryout?: T;
  attempt?: T;
  status?: T;
  program?: T;
  amount?: T;
  paymentDate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}